import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import localFont from 'next/font/local'

import "./globals.css";

const FiraCode = localFont({
  src: '../public/fonts/FiraCode.ttf',
  variable: '--font-fira',
  weight: '100 900',
})

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${FiraCode.variable} ${geistMono.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
